[NLU-3229] - V3 Entity Improvement: 2 digit year
purecloudlabs/Recognizers-Text pull request #51
Opened 2022-12-12 13:44 UTC by Conor-Keaney

Fix for "Month YY" e.g. "March 98"

2022-12-14 10:11 UTC, samhickey25 commented
LGTM are there any other tests that can be unskipped?

2022-12-14 10:11 UTC, samhickey25 approved these changes

2022-12-14 15:09 UTC, Conor-Keaney commented
> LGTM are there any other tests that can be unskipped?

It doesn't appear so, however it seems that there are tests that have been marked as skip for python but are passing for the DatePeriodParser that are unrelated to these changes, I checked and they are also passing on develop. I wont include them in this PR as they are unrelated but just to note, they are as follows :

- `I'll be out the last week of july`
- `schedule a meeting in two weeks`
- `I'll be out in 3 years`
- `first week of 2015`
- `last week of 2015`
- `In nineteen twenty eight`
- `In one thousand seven hundred and eighty nine`
- `Cortana can find us a time beginning of next week`
- `Sure, let's get a Skype end of next week`
- `Sure, let's get a Skype start of next week`
- `Cortana, find us a time end of March`
- `Cortana, please find us a time mid next week`
- `I can find us a time beginning of next week`
- `schedule a meeting in couple of weeks`
- `I'll be out between January 1st and April 5th`
- `I'll be out from Feb 1st to March 2019`
- `I'll be out between Feb 1st and March 2019`
- `Please find us a time to meet later this week`
- `please schedule a meeting for the week commencing february 4`

2022-12-14 16:07 UTC, sanhal commented
@Conor-Keaney , stories mentions all languages , but this PR is only for english

2022-12-15 09:29 UTC, Conor-Keaney commented
> @Conor-Keaney , stories mentions all languages , but this PR is only for english

Added functionality and testing for Dutch, German, French, Italian, Spanish and Portuguese. 
French and Portuguese didn't need any changes for the tests to pass

2022-12-15 09:56 UTC, samhickey25 approved these changes

2022-12-15 10:27 UTC, Conor-Keaney commented
MS PR - https://github.com/microsoft/Recognizers-Text/pull/3057

2023-01-06 01:10 UTC, srandal requested changes

2023-01-06 01:10 UTC, srandal commented on Specs/DateTime/English/DatePeriodParser.json
> +    "Input": "Show me the records for August 99",
Can you add `Show me the records for August 20`? I think the change will break en-US, where that is more likely to mean 2023-08-20 than 2020-08-01.
For en-US, a 2-digit number after a month should default to DD unless it's greater than 31 (or preceded by an apostrophe).
Is there a way to separate en-US behavior from the other Englishes?

2023-01-06 09:29 UTC, Conor-Keaney commented on Specs/DateTime/English/DatePeriodParser.json
> +    "Input": "Show me the records for August 99",
Hey Scott, tested this locally, and yes for `Show me the records for August 20` returns `2022-08-20` / `2023-08-20`. I'll add this test case for en-us

2023-01-06 09:42 UTC, colm-dillon approved these changes

2023-01-06 09:56 UTC, Conor-Keaney commented on Specs/DateTime/English/DatePeriodParser.json
> +    "Input": "Show me the records for August 99",
This was the expected behavior for all languages prior to this change when there isn't something denoting this is a year e.g. 'de' in Spanish, so no breaking changes.

2023-01-06 10:26 UTC, kevinwalshgen approved these changes

2023-01-06 10:30 UTC, andrew-gradinari approved these changes

2023-01-06 11:20 UTC, Conor-Keaney commented on Specs/DateTime/English/DatePeriodParser.json
> +    "Input": "Show me the records for August 99",
Due to the above, I don't think it would be advisable to change this, as it would mean removing this functionality from all other languages. If needed this can be looked at in a separate PR for other English locals, but I think this is functioning as intended

2023-01-06 18:16 UTC, srandal approved these changes

2023-01-16 14:14 UTC, merged