[NLU-3508] - MS Recognisers python - Japanese Date to parity with .NET
purecloudlabs/Recognizers-Text pull request #86
Opened 2023-07-03 16:35 UTC by Conor-Keaney

2023-07-10 09:07 UTC, colm-dillon approved these changes

2023-07-10 09:07 UTC, colm-dillon commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/CJK/base_datetimeperiod.py
> +        # if RegExpUtility.get_group(match, Constants.WITHIN_GROUP_NAME):
Lets just remove these commented snippets if they won't be used.

2023-07-10 09:07 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/common_configs.py
> +        self._unit_value_map = JapaneseDateTime.ParserConfigurationUnitValueMap
`JapaneseDateTime.DurationUnitValueMap`

2023-07-10 09:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/common_configs.py
> +        # TODO Add these once they have been implemented
Where did this come from?

2023-07-10 09:14 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +    def dynasty_year_regex(self):
NIT: `dynasty_year_regex -> Pattern:`

2023-07-10 09:14 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +    def dynasty_start_year_regex(self):
NIT: `def dynasty_start_year_regex(self) -> str:`

2023-07-10 09:20 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +    def date_regex_list_1(self) -> Pattern:
we don't need all the `date_regex_list_1` here

2023-07-10 09:22 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +    @property
Everything from here down isn't needed?

2023-07-10 09:24 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +            self.special_day_with_num_regex, self.special_day_regex, self.this_regex, self.last_regex,
missing `self.next_regex`

2023-07-10 10:09 UTC, samhickey25 requested changes

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +        self._date_regex_list_1 = RegExpUtility.get_safe_reg_exp(JapaneseDateTime.DateRegexList1)
load of comments from dotnet explaining each date lists purpose, could you add them here

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        self._cardinal_extractor = JapaneseCardinalExtractor()
is this needed?

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        self._integer_extractor = JapaneseIntegerExtractor()
`config.integer_extractor`

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        self._ordinal_extractor = JapaneseOrdinalExtractor()
`config.ordinal_extractor`

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        self._number_parser = CJKNumberParser(JapaneseNumberParserConfiguration())
`config.number_parser`

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        self._next_re = RegExpUtility.get_safe_reg_exp(JapaneseDateTime.NextPrefixRegex)
`JapaneseDateExtractorConfiguration.NextRe`

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        self._last_re = RegExpUtility.get_safe_reg_exp(JapaneseDateTime.LastPrefixRegex)
JapaneseDateExtractorConfiguration.lastRe

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        self._unit_regex = RegExpUtility.get_safe_reg_exp(JapaneseDateTime.DateUnitRegex)
`JapaneseDateExtractorConfiguration.UnitRegex`

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        self._date_regex_list = (JapaneseDateExtractorConfiguration()).date_regex_list
All the below regexes are from `JapaneseDateExtractor`, not from `JapaneseDateTime`

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        self._token_last_regex = RegExpUtility.get_safe_reg_exp(JapaneseDateTime.LastPrefixRegex)
these 2 token regexes aren't in dotnet?

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        self._month_of_year = JapaneseDateTime.ParserConfigurationMonthOfYear
the above 5 are called from the config ie `config.cardinal_map`

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        # Regex precedence where the order between D and M varies is controlled by DefaultLanguageFallback
is any of this needed?

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        if self.plus_one_day_regex.search(source):
`RegExpUtility.match_begin(self.plus_one_day_regex, source)`

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        elif self.minus_one_day_regex.search(source):
`RegExpUtility.match_begin(self.minus_one_day_regex, source)`

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        elif self.plus_three_day_regex.search(source):
before this add `if RegExpUtility.exact_match(self.plus_one_day_regex, source)`

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        elif self.plus_three_day_regex.search(source):
and all the following conditionals are exact matches

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +        elif self.plus_two_day_regex.search(source):
before this add if RegExpUtility.exact_match(self.minus_one_day_regex, source)

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +    def get_swift_month(self, source: str) -> int:
where has this come from?

2023-07-10 10:09 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +    def is_cardinal_last(self, source: str) -> bool:
where did this come from?

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +    def month_of_year_regex(self) -> Pattern:
should this be `month_of_date_regex`

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +    def year_to_year_regex(self) -> Pattern:
nit remove regex from the name

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +    def year_to_year_suffix_required_regex(self) -> Pattern:
nit remove regex from the name

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +    def month_to_month_regex(self) -> Pattern:
nit remove regex from the name

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +    def month_to_month_suffix_required_regex(self) -> Pattern:
nit remove regex from the name

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +    def day_to_day_regex(self) -> Pattern:
nit remove regex from the name

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +    def month_day_regex(self) -> Pattern:
name should be `month_day_range`

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +    @property
the properties from here down, except for integer_extractor, date_point_extractor and duration_extractor are not needed?

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +        self._from_prefix = RegExpUtility.get_safe_reg_exp(JapaneseDateTime.DateTimePeriodFromPrefixRegex)
`from_suffix`, `from_prefix` and `_zhijian_regex` are not needed?

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +        self._simple_cases_regexes = [
don't need to call from the resource file, these are all self.simple_case_regex etc

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +        return self._simple_cases_regex
this is defined twice, you're going to need to change the name of one of them

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +        self._cardinal_extractor = JapaneseCardinalExtractor()
don't need cardinal, ordinal, number, now or ambiguity

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +        # TODO When the implementation for these properties is added, change the None values to their respective Regexps
think you can get rid of all of these

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +        self._duration_extractor = None
keep this

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_extractor_config.py
> +    def get_between_token_index(self, source : str) -> MatchedIndex:
where did these functions come from?

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_parser_config.py
> +
you need wo_m_last_regex, wo_m_previous_regex and wo_m_next_regex

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_parser_config.py
> +    def month_of_year(self) -> Pattern:
this returns a dict

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_parser_config.py
> +        raise NotImplementedError
return `self._duration_parser` please

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_parser_config.py
> +    def date_period_with_ago_and_later(self) -> Pattern:
`date_point`

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_parser_config.py
> +        self._date_parser = BaseCJKDateParser(JapaneseDateParserConfiguration(config))
parsers and extractors come from config -> config.integer_extractor

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_parser_config.py
> +        self._dynasty_year_regex = RegExpUtility.get_safe_reg_exp(JapaneseDateTime.DynastyYearRegex)
all regex comes from either `JapaneseDatePeriodExtractorConfiguration` or `JapaneseDateExtractorConfiguration`

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_parser_config.py
> +    def is_month_to_date(self, source: str) -> bool:
where did this come from?

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_parser_config.py
> +        elif self._last_year_regex.search(source):
should be self.last_year_regex

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_parser_config.py
> +    def is_future(self, source) -> bool:
where did this come from?

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_parser_config.py
> +    def is_last_cardinal(self, source) -> bool:
where did this come from?

2023-07-10 11:13 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/dateperiod_parser_config.py
> +    def get_swift_day_or_month(self, source: str) -> int:
where did this come from?

2023-07-10 11:33 UTC, Conor-Keaney commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/CJK/base_datetimeperiod.py
> +        # if RegExpUtility.get_group(match, Constants.WITHIN_GROUP_NAME):
I think this is fine in the cases of duration where this will be added in the next PR that is being worked on at the moment, it can be used as a reminder

2023-07-10 15:46 UTC, Conor-Keaney commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +    def get_swift_month(self, source: str) -> int:
required in base_date line 931 parse_weekday_of_month so had to add it here

2023-07-10 16:03 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/merged_extractor_config.py
>  class JapaneseMergedExtractorConfiguration(CJKMergedExtractorConfiguration):
can you change the order back to what it was?

2023-07-10 16:03 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/merged_parser_config.py
>      def __init__(self, config):
revert this

2023-07-10 16:03 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/utilities/date_utils.py
> +    WEEK_DAY_COUNT = 7
These should be in Constants.py

2023-07-10 16:03 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_parser_config.py
> +    def get_swift_month(self, source: str) -> int:
ah I see, it shouldn't be. see Line 607 on from `.NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/BaseCJKDateParser.cs`

2023-07-11 15:52 UTC, samhickey25 approved these changes
mostly nitty comments

2023-07-11 15:52 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +    def dynasty_start_year_regex(self) -> Pattern:
should this not be just `dynasty_start_year` and only return a string

2023-07-11 15:52 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +    def this_prefix_regex(self) -> Pattern:
A couple of things here have a different name to the dotnet counterpart. Need to be careful when copying over the dotnet code which might then reference the dotnet names
ie this is `ThisRe` not `ThisPrefixRegex`

2023-07-11 15:52 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +    def number_parser(self) -> CJKNumberParser:
is this needed? not in dotnet

2023-07-11 15:52 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +        self._ordinal_extractor = JapaneseOrdinalExtractor()
don't need this

2023-07-11 15:52 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +        self._number_parser = CJKNumberParser(JapaneseNumberParserConfiguration())
or this

2023-07-11 15:52 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +        self._preposition_regex = RegExpUtility.get_safe_reg_exp(JapaneseDateTime.PrepositionRegex)
couple of things here like this which aren't part of a property, can be removed

2023-07-11 15:52 UTC, samhickey25 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +        self._dynasty_start_year_regex = RegExpUtility.get_safe_reg_exp(JapaneseDateTime.DynastyStartYear)
yeah this isn't a regex, just a string

2023-07-12 09:26 UTC, KanchanKumar12 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/CJK/base_date.py
> +        # tokens.extend(self.duration_with_ago_and_later(source, reference))
should be uncommented?

2023-07-12 09:26 UTC, KanchanKumar12 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/CJK/base_date.py
> +        # duration_extracted_results = self.config.duration_extractor.extract(source_text, reference)
Do we need to figure this chunk out ? What is the reason for commenting it?

2023-07-12 09:26 UTC, KanchanKumar12 commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/japanese/date_extractor_config.py
> +        if JapaneseDateTime.DefaultLanguageFallback == Constants.DEFAULT_LANGUAGE_FALLBACK_DMY:
nit: add comment

```
// 2016/12 (this is not a Date)
// var dateRegex11 = new Regex(DateTimeDefinitions.DateRegexList11, RegexFlags);
// Regex precedence where the order between D and M varies is controlled by DefaultLanguageFallback
```

2023-07-12 09:28 UTC, KanchanKumar12 approved these changes

2023-07-12 09:43 UTC, Conor-Keaney commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/CJK/base_date.py
> +        # duration_extracted_results = self.config.duration_extractor.extract(source_text, reference)
Duration is not involved in this ticket

2023-07-12 09:43 UTC, Conor-Keaney commented on Python/libraries/recognizers-date-time/recognizers_date_time/date_time/CJK/base_date.py
> +        # tokens.extend(self.duration_with_ago_and_later(source, reference))
Duration is not involved in this ticket

2023-07-12 15:46 UTC, merged